### ISSUE TITLE
Add Server class

### ISSUE THREAD

**Issue by merkys** [EnjoyCpp/jsonapi-client-cpp#11]
Class `Server` should have only one attribute `URL` with a setter/getter pair. It should as well have the following public methods:
* `get_all( type )` – returns an array of `Resource` objects of type (by querying `URL` + '/' + `type`);
* `get_one( type, id )` – returns a single `Resource` object (by querying `URL` + '/' + `type` + '/' + `id`).
Later on other methods will be added.

**Comment by EnjoyCpp** [comment]
@merkys not sure how to do get_all( type ) and get_one( type, id ) methods properly.

**Comment by merkys** [comment]
@EnjoyCpp both methods have to fetch JSON by URL (I see URLs are already constructed in `src/server.cpp`). Then from `data` in returned JSON `Resource` objects have to be constructed. Maybe a separate constructor for `Resource` object could be introduced as `Resource::Resource( Json::Value value )`. Then `Resource` constructor could be called with all items from `data` payload.

**Comment by EnjoyCpp** [comment]
@merkys if I am right i have to use similar method I used in test.cpp to get jsoncpp?

**Comment by merkys** [comment]
@EnjoyCpp Exactly :)

**Comment by EnjoyCpp** [comment]
@merkys Having a hard time with server class but tried to do something but I don't think it will be correct.

**Comment by merkys** [comment]
OK, I hope these steps will help you to get on the track:

- [x] Move the JSON fetching code from `src/main.cpp` to `src/server.cpp` as a new private method `Json::Value get_URL(const std::string URL)`

- [x] Add private field `Json::Value JSON` to `src/Resource.cpp`

- [ ] In `src/server.cpp` in `get_one()`, use `get_URL()` to fetch the JSON by the constructed URL and then create new Resource by passing `JSON['data']`, where `JSON` is a variable storing the JSON returned by `get_URL`.

**Comment by merkys** [comment]
@EnjoyCpp Let me know should you have any trouble in dealing with third step.

**Comment by EnjoyCpp** [comment]
@merkys ye I have problems with third step with creating new resource

**Comment by merkys** [comment]
Opened PR #16. This should at least point to the right direction.

**Comment by EnjoyCpp** [comment]
@merkys maybe now it is a little better

**Comment by merkys** [comment]
In principle yes, but `Server::get_all` has to return an array of `Resource` (I believe it is possible in C++).

**Comment by EnjoyCpp** [comment]
@merkys honestly thinking about get_all problem for a long time and I cant find any working solution how to separate JSON array from URL to objects to put them in to array. So, maybe you have any suggestions for that?

**Comment by merkys** [comment]
I have implemented `get_all()` using `std::list<Resource>` in #37. This way a list of `Resource` objects is returned, to be examined by the receiver.
