### ISSUE TITLE
Resource::set_attribute()

### ISSUE THREAD

**Issue by merkys** [EnjoyCpp/jsonapi-client-cpp#20]
Implement the following attribute setters for `Resource`:
* `set_attribute( const std::string name, bool value )`
* `set_attribute( const std::string name, std::string value )`
* `set_attribute( const std::string name, int value )`
* `set_attribute( const std::string name, double value )`

**Comment by merkys** [comment]
Thanks!

Nevertheless, for time being the return types of these methods should be `void` instead of `std::string`, as they will return nothing. Moreover, the setters should modify the JSON (stored in `JSON` variable) instead of `attribute_name_`. Basically, you have to store the `value` in `JSON[attribute_name]`.

**Comment by EnjoyCpp** [comment]
@merkys now it should be better

**Comment by merkys** [comment]
Yes, it seems to be working now.

I suggest replacing
```
        std::map<std::string, *> mapOfJson;
        //Inserting data in std::map
        mapOfJson[name]=value;
        JSON["attributes"][name]=mapOfJson[name];
```
with just
```
        JSON["attributes"][name] = value;
```
This should work, and `std::map` is no longer needed, since everything is stored in the JSON directly.

The following symbols can be safely removed:
* `std::string attribute_name_`
* `std::string value_`
* `Resource(const std::string attribute_name="",const std::string value="")`
* `std::string set_attribute(const std::string atribute_name, const std::string value )`
