### ISSUE TITLE
Resource needs to know its Server

### ISSUE THREAD

**Issue by merkys** [EnjoyCpp/jsonapi-client-cpp#26]
Currently, `Resource` object does not know its server, but in future (#27) it will need to. Thus `Resource` should have a private field `server` for its server. A getter/setter pair is also needed.

Secondly, `Resource` constructor has to be modified to always require and `Server`:
```cpp
Resource(Server server, Json::Value value)
```
In `Server::get_one()` and `Server::get_all()` the `Server` has to pass itself to the constructors of `Resource`.

**Comment by EnjoyCpp** [comment]
@merkys Having a really hard time with Resource files and Server with naming types

**Comment by EnjoyCpp** [comment]
@merkys These problems only occurs when including Server.h header in to Resource.h header and Resource.h header in to Server.h header and i don't really know how to solve this problem.

**Comment by merkys** [comment]
There is a C/C++ trick called [Include guard](https://en.wikipedia.org/wiki/Include_guard), it may help in this situation. Try it, and let me know should there still be any problems.

**Comment by EnjoyCpp** [comment]
@merkys  i have #pragma once in my headers also i tried #ifndef #define but it didn't help

**Comment by merkys** [comment]
OK, I will check.

**Comment by merkys** [comment]
Fixed in #30, please check.

**Comment by merkys** [comment]
This is already implemented, closing.
