### ISSUE TITLE
Resource::get_server() and Resource::set_server() should use Server objects instead of strings

### ISSUE THREAD

**Issue by merkys** [EnjoyCpp/jsonapi-client-cpp#32]
The following getter/setter pair treats server as a string while it must be an object:

https://github.com/EnjoyCpp/jsonapi-client-cpp/blob/a1b4b332df091b7bbfe6a94c8b21f10ecf5fcac5/src/Resource.h#L35-L36

Instead, they should be
```C++
Server* get_server();
void set_server( Server* server );
```

**Comment by EnjoyCpp** [comment]
@merkys something like it?

**Comment by merkys** [comment]
Yes, now the setters/getter is correct. Thanks.
