### ISSUE TITLE
Deduplicate code in Server.c

### ISSUE THREAD

**Issue by merkys** [EnjoyCpp/jsonapi-client-cpp#41]
`Server` methods `create()` and `update()` share a lot of common code. I suggest deduplicating it.

**Comment by EnjoyCpp** [comment]
@merkys Deduplicated code by adding new method. Also checked with tests and seems to work correctly

**Comment by merkys** [comment]
Looks good. Two suggestions:

- [x] Rename `Resource::information` to `Resource::send_json_to_server`, as `information` is overly generic name;
- [x] Make `Resource::information` (now `Resource::send_json_to_server`) private instead of public.
