### ISSUE TITLE
set_attribute() converts strings to boolean values

### ISSUE THREAD

**Issue by merkys** [EnjoyCpp/jsonapi-client-cpp#46]
Quoting @EnjoyCpp:
> Also i spotted  one mistake when i try to set value of attribute using string type it shows wrong value.
For example trying to set value for attribute name ( `set_attribute("name","Pablo Picasso")`);
In JSON shows `"name" : true`
And in the POSTED data to the website  `name: "1".`
So think there is a mistake in this setter that i will try to solve:
https://github.com/EnjoyCpp/jsonapi-client-cpp/blob/feac235d59dc55f374c801fc25b2b3702b87c602/src/Resource.cpp#L27-L28

_Originally posted by @EnjoyCpp in https://github.com/EnjoyCpp/jsonapi-client-cpp/issues/27#issuecomment-633981205_

**Comment by EnjoyCpp** [comment]
@merkys adding a `const char *` setter doesn't fix this problem. All other setters seems to work fine.

**Comment by merkys** [comment]
> @merkys adding a `const char *` setter doesn't fix this problem. All other setters seems to work fine.

I do not see a `const char *` setter in the code, there is only a `const char` setter, maybe this is the problem?

**Comment by EnjoyCpp** [comment]
@merkys `const char *` setter works. So i deleted `std::string` and `const char` setters

**Comment by merkys** [comment]
Thanks. Closing the issue as resolved.
